# Generated by Django 5.2 on 2025-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_product_specs_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_in_list',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
