# Generated by Django 5.2 on 2025-06-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
